// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZ47zUNUIQfpSt4Yk7k5kNRszVMl7nnJQ',
    appId: '1:723181195464:web:a6713c984105fb569555fd',
    messagingSenderId: '723181195464',
    projectId: 'alogyan-prep1',
    authDomain: 'alogyan-prep1.firebaseapp.com',
    storageBucket: 'alogyan-prep1.firebasestorage.app',
    measurementId: 'G-RPQ5E5DSKH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZnPNTSEbnHBthJb5lUk8A_1WnNkWrSZg',
    appId: '1:723181195464:android:b5f0646498d221779555fd',
    messagingSenderId: '723181195464',
    projectId: 'alogyan-prep1',
    storageBucket: 'alogyan-prep1.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOJbgxDAHrXY3O6aDnBnPFNhn3xjTTZqI',
    appId: '1:723181195464:ios:f3cb6d3fd5afa2389555fd',
    messagingSenderId: '723181195464',
    projectId: 'alogyan-prep1',
    storageBucket: 'alogyan-prep1.firebasestorage.app',
    iosBundleId: 'com.example.alogyanPrep',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOJbgxDAHrXY3O6aDnBnPFNhn3xjTTZqI',
    appId: '1:723181195464:ios:f3cb6d3fd5afa2389555fd',
    messagingSenderId: '723181195464',
    projectId: 'alogyan-prep1',
    storageBucket: 'alogyan-prep1.firebasestorage.app',
    iosBundleId: 'com.example.alogyanPrep',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZ47zUNUIQfpSt4Yk7k5kNRszVMl7nnJQ',
    appId: '1:723181195464:web:96da604075d4e1da9555fd',
    messagingSenderId: '723181195464',
    projectId: 'alogyan-prep1',
    authDomain: 'alogyan-prep1.firebaseapp.com',
    storageBucket: 'alogyan-prep1.firebasestorage.app',
    measurementId: 'G-TZ0HHG0BNK',
  );
}
